In [5]:
import numpy as np

In [7]:
a = np.random.rand(2,3,2,3)
a

array([[[[0.86589685, 0.75372333, 0.93015184],
         [0.59137699, 0.44690727, 0.52850128]],

        [[0.20734365, 0.7611772 , 0.11953056],
         [0.93324817, 0.55304288, 0.33966875]],

        [[0.70323172, 0.51067081, 0.91494927],
         [0.63115837, 0.57632926, 0.73780021]]],


       [[[0.46763998, 0.29353689, 0.8056899 ],
         [0.66707958, 0.71777654, 0.61862266]],

        [[0.95881244, 0.1178572 , 0.60942978],
         [0.97787304, 0.62107035, 0.0541298 ]],

        [[0.76025469, 0.60738885, 0.16687166],
         [0.07300342, 0.73252417, 0.85482429]]]])

In [10]:
a.reshape(a.shape[0], -1)

array([[0.86589685, 0.75372333, 0.93015184, 0.59137699, 0.44690727,
        0.52850128, 0.20734365, 0.7611772 , 0.11953056, 0.93324817,
        0.55304288, 0.33966875, 0.70323172, 0.51067081, 0.91494927,
        0.63115837, 0.57632926, 0.73780021],
       [0.46763998, 0.29353689, 0.8056899 , 0.66707958, 0.71777654,
        0.61862266, 0.95881244, 0.1178572 , 0.60942978, 0.97787304,
        0.62107035, 0.0541298 , 0.76025469, 0.60738885, 0.16687166,
        0.07300342, 0.73252417, 0.85482429]])

In [2]:
a = [[1,2], [4,5]]
b = [[4,5], [7,8]]

In [7]:
c = np.multiply(a, b)
c

array([[ 4, 10],
       [28, 40]])

In [58]:
box1 = (-2, 1, 4, 3)
box2 = (1, 2, 3, 4)

xx = abs(box1[0])
xx

2